[package]
name = "rlox_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake = { version = "2.5.0", features = ["derive"] }
rand = "0.8.5"

[dev-dependencies]
drop-tracker = "0.1.0"

