[package]
name = "rlox_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24"
strum_macros = "0.24"
rlox_common = { path = "../rlox_common" }
rustc-hash = "1.1.0"
